---
title: "Independent Project: Proposed Workflow"
subtitle: "A web-based application for viewing and exporting gps data in large, collaborative study"
author: "Luke Wilde"
date: "4/17/2022"
output: pdf_document
bibliography: Wilde_IndepProj_citations.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Directions

This document is required to be 1 page (but can be more), overviewing your proposed project. It must be completed in R Markdown and knit to a pdf. The aim here is to lay out the scope, data set(s), and functions you propose to use for your individual project. You must upload your .Rmd file, knit .pdf, and .bib file to WyoCourses.

1.	A 1-2 paragraph overview of your goals. What topic are you addressing? Why is this topic important and what knowledge gap does it fill? How does it relate to your previous research and/or to previous literature? Include at least 3 citations, linking your .bib file and .Rmd file.

# Goals and Topic
*Answer here*

2.	An overview of your dataset(s). Describe the dataset(s) you plan to use. How are they formatted? What challenges to you foresee arising when analyzing/visualizing these datasets?

# Dataset Overview
*Type here*

3.	An overview of proposed workflow. What workflow will you implement? What topics generally from class will you use in implementing your workflow? What packages and functions (more specifically) from class will you use?

# Workflow Overview
*Type*

If you will use packages and functions that are not covered in class and are not part of Base R (i.e. where you need to load any libraries), please briefly describe them.
*Type*

You are welcome to incorporate code beyond what we’ve discussed in class, but your workflow must also directly include concepts and functions we have covered during the semester. You are welcome to incorporate ideas presented in group projects as well!
*Type*

# References

<div id="refs"></div>

# Supporting Materials
